# Project-wide Gradle settings.
org.gradle.java.home=D:/Java/jdk-17.0.2
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
android.nonTransitiveRClass=true
android.overridePathCheck=true
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
